services:
  node:
    container_name: node_jwt-verify
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    tty: true
    volumes:
      - ./src:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_OUTPUT=${AWS_DEFAULT_OUTPUT}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
